# Generated by Django 5.1.5 on 2025-02-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to='books/'),
            preserve_default=False,
        ),
    ]
